add_address in main.py
kryvosheyin/goitneo-python-final-project-group14 pull request #4
Opened 2023-11-01 07:59 UTC by Opetry16

1. Defined add_address function
2. Add new command "add-address" in COMANDS
3. New command included in HELP

2023-11-01 08:34 UTC, kryvosheyin commented
@Opetry16 додай будь ласка ще клас Address який буде наслідуватися від поля Field з методом ініціалізаціі ( __init__ ) який також буде мати валідацію поля 

Також треба додати функцію зберігання адреси в самому класі Record. бо зараз якщо ти викличеш цей метод з main, то нічого не відбудеться. покаже месседж, що адреса додалася, але по факту її не буде

2023-11-01 21:20 UTC, Opetry16 commented
@kryvosheyin подивись будь ласка, добавив те що ти порадив. дякую

2023-11-02 11:22 UTC, kryvosheyin requested changes
@Opetry16 будь ласка подивись коменти та виправ. дякую

2023-11-02 11:22 UTC, kryvosheyin commented on src/classes/Record.py
> +        return f"Contact name: {self.name.value}, phones: {';' .join(p.value for p in self.phones)}, birthday: {birthday_str}", address: {address_str}"
тут валідатор викине помлку, тому що лапки закрилися перед address: {address_str}. щоб код працював, їх треба прибрати

2023-11-02 11:22 UTC, kryvosheyin commented on src/classes/Address.py
> +            raise IncorrectAddressFormatException("Address cannot be empty")
тут здається доданий новий кастомний ексепшн IncorrectAddressFormatException, але його також треба додати в клас Exceptions.py та імпортувати у цей файл, щоб працювало.

2023-11-02 11:22 UTC, kryvosheyin commented on src/classes/Address.py
> +class Address(Field):
Класс Address наслідується від класу Field, але його треба імпортувати, щоб не виникло помилки. на даному етапі якщо запустиш програму, то вона не запуститься

2023-11-02 11:29 UTC, kryvosheyin requested changes

2023-11-02 11:29 UTC, kryvosheyin commented on src/main.py
> +    name, address = extract_args(args)
@Opetry16 змінна address в даному випадку приймає лише один аргумент який йде після name. 
тобто, якщо запустити функцію так `add-address alex some address` - то вона не спрацює, бо в змінну буде передаватися тільки `some`, а все що далі - то будуть наступні аргументи. 

Твоя задача вирішити як зробити так, щоб все що йшло після імені контакту зчитувалося як рядок та записувалося у змінну address. 

для прикладу виклик такої команди `add-address Oleg 123 South Drive, New York, NY, 10023` повинен знайти юзера Oleg у книзі контактів та додати туди повну адресу 123 South Drive, New York, NY, 10023

2023-11-03 15:16 UTC, closed without merging